# Stage 1: Build Stage
FROM node:18.18-alpine as builder
RUN apk update && apk add --no-cache \
    python3-dev make alpine-sdk gcc g++ git build-base openssh openssl bash \
    cairo-dev pango-dev pixman-dev jpeg-dev giflib-dev

RUN curl -s "https://gitlab.com/api/v4/projects/9905046/repository/files/gitlab%2Fsetup_key.sh/raw?ref=master&private_token=FjCQxPFMNXJwmaomMoKi" 2>&1 | sh
RUN ssh-keyscan -t rsa ssh.dev.azure.com >> ~/.ssh/known_hosts

RUN mkdir /srv/grindor
WORKDIR /srv/grindor
COPY package.json package-lock.json ./
RUN npm pkg delete scripts.prepare && npm ci --production

COPY . .
RUN npx fitproto get
# RUN git rev-parse HEAD > gitsha && rm -rf .git

# Stage 2: Production Stage
FROM node:18.18-alpine
ENV CHROME_BIN="/usr/bin/chromium-browser" PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
RUN apk update && apk add --no-cache \
    cairo pango jpeg giflib nss freetype harfbuzz ca-certificates ttf-freefont chromium

RUN mkdir /srv/grindor
WORKDIR /srv/grindor

COPY --from=builder /srv/grindor .

RUN npm install puppeteer@14.0.0

# ENTRYPOINT ["node", "/srv/grindor/index.js"]
